### PR TITLE
Laravel 9.0 Compatibility

### PR DESCRIPTION
**Pull request by gofish543**
## Description

This PR brings laravel-page-speed up to Laravel 9.0 Compatibility with issue #161

### CODE REVIEW

**Comment by swapnilsarwe** [comment]
any chances this getting merged before Laravel 9 release?

**Comment by AbdallaMohammed** [comment]
I hope anyone will merge this soon

**Comment by davidldear** [comment]
Bumping so we can hopefully go to 9.0 as well.

**Comment by padre** [comment]
@renatomarinho will this package be updated for Laravel 9 support?

Thanks!

**Comment by BramImhof** [comment]
@renatomarinho could you please merge this? :)

**Comment by swapnilsarwe** [comment]
Hello Everyone,

@gofish543 has already made effort to create a PR for the Laravel 9 support, many thanks to him.

Till the time @renatomarinho gets time to check this and merge, I would suggest people to use the @gofish543 fork in the meanwhile, rather than posting & pushing @renatomarinho to get this merged. Let him take his time from his schedule and get it done peacefully.

If you need help how to get that done.

Following is the way:
In `composer.json`

To do so, temporarily add @gofish543 fork to the repositories property of your composer.json:


```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/gofish543/laravel-page-speed.git"
        }
    ]
}
``` 

Then update your dependency constraint to reference this branch:
```
{
    "require": {
        "renatomarinho/laravel-page-speed": "dev-laravel9.0",
    }
}
```

Finally, run: `composer update`

**Comment by joaorobertopb** [comment]
Thanks @gofish543 !

**Pull request merged**
