### PR TITLE
Fixed Auto-Discover

### LINKED ISSUE #88: Auto Discovery NOT Working
Auto Discovery NOT Working on fresh Laravel 5.5.*

## Detailed description

First I want to thanks you for making this Amazing package in open source community, Actually After installing this package on fresh laravel 5.5.* It is not working so I forced to add the middleware and Serviceproviders my self,  after that It working fine.

### PR DESCRIPTION
**Pull request by stakahashi**
## Description

Auto-Discover was fixed. In addition, we set a setting value that does not load unnecessary middleware.

## Motivation and context

fixed #88 

## How has this been tested?

```composer test```

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [ ] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by joaorobertopb** [comment]
Thanks for contribution! :smile: 

@stakahashi This PR requires a change in documentation. Please, update the Readme file.

Great work!

**Comment by joaorobertopb** [comment]
**Note:** Autodiscover is currently working! But, the middlewares should be registered in "Kernel.php" manually. :sweat_smile:

This PR will prevent the manual registration of middlewares!

**Comment by stakahashi** [comment]
@joaorobertopb README.md updated.

**Comment by stakahashi** [comment]
@joaorobertopb I understand. This PR is closed.

**Pull request closed without merging**
