### PR TITLE
[2.x] Implementation of defer_javascript

### PR DESCRIPTION
**Pull request by f-liva**
It implements the Defer Javascript middleware

### CODE REVIEW

**Comment by f-liva** [comment]
Is this project still alive?

**Comment by joaorobertopb** [comment]
@f-liva thanks for the PR!!

At the moment, the priority is to merge #111

**Comment by joaorobertopb** [comment]
Hey @lucasMesquitaBorges , let's move this **PR** to **2.x** branch?

**Comment by lucasMesquitaBorges** [comment]
I agree @joaorobertopb! Moved to 2.x target branch and added onto [milestone 2.0.0](https://github.com/renatomarinho/laravel-page-speed/milestone/1).

Later I'll rebase it to remove conflicts added after changing target branch.

**Comment by joaorobertopb** [comment]
Nice!

**Pull request merged**
