### PR TITLE
Added PHP 8 Support from 2.x branch

### PR DESCRIPTION
**Pull request by lakuapik**
## Description

Basically just a copy of this https://github.com/renatomarinho/laravel-page-speed/pull/139/commits/022f1a867cbfdf8c7774293552eae8a129e61ae0 and use `2.x` branch instead of `master` branch.

## Motivation and context

Please support PHP 8, we need this.

## How has this been tested?

Not tested.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by lakuapik** [comment]
Context: https://github.com/renatomarinho/laravel-page-speed/pull/139#issuecomment-738765392

**Comment by lucasMesquitaBorges** [comment]
Thank you @lakuapik for you contribution!

**Comment by mennorenkens** [comment]
@lucasMesquitaBorges Any idea when the 2.0.0 version including PHP 8.0 support will be released?

**Comment by joaorobertopb** [comment]
Thanks!

**Pull request merged**
